services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/gateway-api/src           # Mount the local src directory
      - ./target:/gateway-api/target       # Mount the local target directory
      - ./mvnw:/gateway-api/mvnw           # Mount the mvnw script
      - ./pom.xml:/gateway-api/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8081:8081"                     # Map port 8091 to the host
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge