FROM openjdk:17-jdk-slim

# Set the working directory to /gateway-api
WORKDIR /gateway-api

# Copy Maven Wrapper, pom.xml, and the .mvn folder
COPY mvnw pom.xml ./
COPY .mvn .mvn

# Copy source files into /gateway-api/src
COPY src ./src

# Ensure the mvnw script is executable
RUN chmod +x mvnw

# Copy the entrypoint script into /gateway-api and ensure it’s executable
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Set the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]
