services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/gateway-api/src           # Mount the local src directory
      - ./target:/gateway-api/target       # Mount the local target directory
      - ./mvnw:/gateway-api/mvnw           # Mount the mvnw script
      - ./pom.xml:/gateway-api/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8081:8081"                     # Map port 8091 to the host
    networks:
      - kong-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
    
  websocketBackend:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    image: gateway-websocket-backend
    container_name: websocketBackend
    ports:
      - "8080:8080"
    networks:
      - kong-net
    volumes:
      - ./test_server:/app
    environment:
      PORT: 8080
  
networks:
  kong-net:
    driver: bridge  