
# Keycloak configuratie
keycloak:
  auth-server-url: http://keycloak:8080/realms/Babymonitor
  realm: Babymonitor
  resource: babymonitor-client-api
  bearer-only: true

# Spring security oauth2 resource server configuratie
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/Babymonitor
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


