spring.application.name=gateway_api
server.port=8081
spring.main.web-application-type=reactive

# WebSocket route TODO: Update the URI to point to the actual WebSocket backend service
# ws://dataService:8722/
spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=1048576

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG

spring.cloud.gateway.routes[0].id=websocket-data
spring.cloud.gateway.routes[0].uri=ws://dataservice:8722/
spring.cloud.gateway.routes[0].predicates[0]=Path=/data/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=change
spring.cloud.gateway.routes[1].uri=http://changeService:8082/
spring.cloud.gateway.routes[1].predicates[0]=Path=/change/**

spring.cloud.gateway.routes[2].id=scenario
spring.cloud.gateway.routes[2].uri=http://scenarioService:8083/
spring.cloud.gateway.routes[2].predicates[0]=Path=/scenario/**

# spring.cloud.gateway.routes[3].id=lobby
# spring.cloud.gateway.routes[3].uri=http://lobbyService:8083/
# spring.cloud.gateway.routes[3].predicates[0]=Path=/lobbies/**

# spring.cloud.gateway.routes[4].id=participant
# spring.cloud.gateway.routes[4].uri=http://lobbyService:8083/
# spring.cloud.gateway.routes[4].predicates[0]=Path=/participant/**

# spring.cloud.gateway.routes[5].id=scenario
# spring.cloud.gateway.routes[5].uri=http://scenarioService:8084/
# spring.cloud.gateway.routes[5].predicates[0]=Path=/scenario/**

# spring.cloud.gateway.routes[6].id=result
# spring.cloud.gateway.routes[6].uri=http://resultService:8085/
# spring.cloud.gateway.routes[6].predicates[0]=Path=/api/results/**

# spring.cloud.gateway.routes[7].id=examination
# spring.cloud.gateway.routes[7].uri=http://examinationService:8086/
# spring.cloud.gateway.routes[7].predicates[0]=Path=/api/examination/**

# matlab zou niet direct benaderd moeten worden vanuit de frontend, alleen via RabbitMQ of verbonden Service
# spring.cloud.gateway.routes[8].id=matlab
# spring.cloud.gateway.routes[8].uri=http://matlabService:8087/
# spring.cloud.gateway.routes[8].predicates[0]=Path=/matlab/**


