name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
      - dockerHub
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set the version tag
    - name: Set Docker Tag
      id: set_tag
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          VERSION="main-${{ github.sha }}"
          IMAGE_TAG="latest"  # Tag for the main branch
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          VERSION="dev-${{ github.sha }}"
          IMAGE_TAG="dev-latest"  # Tag for the dev branch
        else
          VERSION="latest-${{ github.sha }}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag babymonitors/gateway:${{ env.VERSION }} --tag babymonitors/gateway:${{ env.IMAGE_TAG }}

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push babymonitors/gateway:${{ env.VERSION }}
        docker push babymonitors/gateway:${{ env.IMAGE_TAG }}
