name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
      - dockerHub
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Get the Git commit SHA (shortened to the first 7 characters)
    - name: Get Commit SHA
      run: |
        COMMIT_SHA=${{ github.sha }}
        SHORT_SHA=${COMMIT_SHA::7}


    # Build the Docker image with both the commit SHA and 'latest' tags
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag babymonitors/gateway:$SHORT_SHA --tag babymonitors/gateway:latest

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push the Docker image to Docker Hub with both tags
    - name: Push Docker image to Docker Hub
      run: |
        docker push babymonitors/gateway:$SHORT_SHA
        docker push babymonitors/gateway:latest
