name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
      - dockerHub
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag babymonitors/gateway:latest

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Docker Hub manually
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}"

    
    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push babymonitors/gateway:latest
